version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: souzitoban_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - app_network
        ports:
            - "8000:8000"

    db:
        image: mysql:8.0
        container_name: souzitoban_db
        restart: always
        environment:
            MYSQL_DATABASE: souzitoban_db
            MYSQL_ROOT_PASSWORD: tatsutora88  # ここだけ残す
        ports:
            - "3306:3306"
        networks:
            - app_network
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: souzitoban_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app_network

networks:
    app_network:

volumes:
    db_data:
